#!/usr/bin/env bash
# frob deploy install.sh
# GENERATED by `frob deploy generate` -- DO NOT EDIT BY HAND.
# Re-run `frob deploy generate` to regenerate after a design change.
# frob-deploy-manifest-digest: 5b791d59d5ed3afe22289d66d609f13cbbc0d8cac49f277b0c6b97e0b80e25a5
set -euo pipefail

echo "--- backup ---"
if ! id -u "malmberg-backup" >/dev/null 2>&1; then
    useradd --system --no-create-home --shell /usr/sbin/nologin "malmberg-backup"
    echo "created service user malmberg-backup"
else
    echo "service user malmberg-backup already present, skipping"
fi
desired_hash="d6501055a8318aba85199d93d845a059bfe43f9f376249706f80e5a7be4a320b"
if [ -f "/etc/systemd/system/frob-deploy-backup.service" ]; then
    current_hash="$(sha256sum "/etc/systemd/system/frob-deploy-backup.service" | cut -d" " -f1)"
else
    current_hash=""
fi
if [ "$current_hash" != "$desired_hash" ]; then
    cat > "/etc/systemd/system/frob-deploy-backup.service" <<'FROB_UNIT_EOF'
[Unit]
Description=frob deploy generated unit for backup

[Service]
User=malmberg-backup
NoNewPrivileges=yes
ProtectSystem=strict
PrivateTmp=yes
ReadWritePaths=/var/lib/malmberg/backup-audit
CapabilityBoundingSet=
SystemCallFilter=brk clone close execve execveat exit exit_group fork mmap munmap read rt_sigreturn vfork write

[Install]
WantedBy=multi-user.target
FROB_UNIT_EOF
    systemctl daemon-reload
    echo "wrote unit frob-deploy-backup.service"
else
    echo "unit frob-deploy-backup.service already up to date"
fi
if ! systemctl is-enabled --quiet "frob-deploy-backup.service" 2>/dev/null; then
    systemctl enable "frob-deploy-backup.service"
    echo "enabled frob-deploy-backup.service"
fi
if ! systemctl is-active --quiet "frob-deploy-backup.service" 2>/dev/null; then
    systemctl start "frob-deploy-backup.service"
    echo "started frob-deploy-backup.service"
fi
desired_mode="0750"
if [ ! -e "/var/lib/malmberg/backup-audit" ]; then
    mkdir -p "/var/lib/malmberg/backup-audit"
    echo "created /var/lib/malmberg/backup-audit"
fi
current_owner="$(stat -c "%U" "/var/lib/malmberg/backup-audit")"
if [ "$current_owner" != "malmberg-backup" ]; then
    chown "malmberg-backup":"malmberg-backup" "/var/lib/malmberg/backup-audit"
    echo "chowned /var/lib/malmberg/backup-audit to malmberg-backup"
fi
current_mode="$(stat -c "%a" "/var/lib/malmberg/backup-audit")"
if [ "${current_mode#0}" != "${desired_mode#0}" ]; then
    chmod "0750" "/var/lib/malmberg/backup-audit"
    echo "chmoded /var/lib/malmberg/backup-audit to 0750"
fi
echo "--- cloudsync ---"
if ! id -u "malmberg-cloudsync" >/dev/null 2>&1; then
    useradd --system --no-create-home --shell /usr/sbin/nologin "malmberg-cloudsync"
    echo "created service user malmberg-cloudsync"
else
    echo "service user malmberg-cloudsync already present, skipping"
fi
desired_hash="0a8f216ff0ce3f63aafb57bdb637401d34d21659df53bc55c3b871b475da364c"
if [ -f "/etc/systemd/system/frob-deploy-cloudsync.service" ]; then
    current_hash="$(sha256sum "/etc/systemd/system/frob-deploy-cloudsync.service" | cut -d" " -f1)"
else
    current_hash=""
fi
if [ "$current_hash" != "$desired_hash" ]; then
    cat > "/etc/systemd/system/frob-deploy-cloudsync.service" <<'FROB_UNIT_EOF'
[Unit]
Description=frob deploy generated unit for cloudsync

[Service]
User=malmberg-cloudsync
NoNewPrivileges=yes
ProtectSystem=strict
PrivateTmp=yes
ReadWritePaths=/var/lib/malmberg/cloud-staging
CapabilityBoundingSet=CAP_NET_BIND_SERVICE
SystemCallFilter=accept bind brk close connect exit exit_group listen mmap munmap read recvfrom rt_sigreturn sendto socket write

[Install]
WantedBy=multi-user.target
FROB_UNIT_EOF
    systemctl daemon-reload
    echo "wrote unit frob-deploy-cloudsync.service"
else
    echo "unit frob-deploy-cloudsync.service already up to date"
fi
if ! systemctl is-enabled --quiet "frob-deploy-cloudsync.service" 2>/dev/null; then
    systemctl enable "frob-deploy-cloudsync.service"
    echo "enabled frob-deploy-cloudsync.service"
fi
if ! systemctl is-active --quiet "frob-deploy-cloudsync.service" 2>/dev/null; then
    systemctl start "frob-deploy-cloudsync.service"
    echo "started frob-deploy-cloudsync.service"
fi
desired_mode="0750"
if [ ! -e "/var/lib/malmberg/cloud-staging" ]; then
    mkdir -p "/var/lib/malmberg/cloud-staging"
    echo "created /var/lib/malmberg/cloud-staging"
fi
current_owner="$(stat -c "%U" "/var/lib/malmberg/cloud-staging")"
if [ "$current_owner" != "malmberg-cloudsync" ]; then
    chown "malmberg-cloudsync":"malmberg-cloudsync" "/var/lib/malmberg/cloud-staging"
    echo "chowned /var/lib/malmberg/cloud-staging to malmberg-cloudsync"
fi
current_mode="$(stat -c "%a" "/var/lib/malmberg/cloud-staging")"
if [ "${current_mode#0}" != "${desired_mode#0}" ]; then
    chmod "0750" "/var/lib/malmberg/cloud-staging"
    echo "chmoded /var/lib/malmberg/cloud-staging to 0750"
fi
echo "--- display ---"
if ! id -u "malmberg-display" >/dev/null 2>&1; then
    useradd --system --no-create-home --shell /usr/sbin/nologin "malmberg-display"
    echo "created service user malmberg-display"
else
    echo "service user malmberg-display already present, skipping"
fi
desired_hash="b90ff0edf23906aba16b1b78bae631037dcf2bfa6c02049def93547574d60c97"
if [ -f "/etc/systemd/system/frob-deploy-display.service" ]; then
    current_hash="$(sha256sum "/etc/systemd/system/frob-deploy-display.service" | cut -d" " -f1)"
else
    current_hash=""
fi
if [ "$current_hash" != "$desired_hash" ]; then
    cat > "/etc/systemd/system/frob-deploy-display.service" <<'FROB_UNIT_EOF'
[Unit]
Description=frob deploy generated unit for display

[Service]
User=malmberg-display
NoNewPrivileges=yes
ProtectSystem=strict
PrivateTmp=yes
ReadWritePaths=/var/lib/malmberg-display
CapabilityBoundingSet=CAP_NET_BIND_SERVICE
SystemCallFilter=accept bind brk clone close connect execve execveat exit exit_group fork listen mmap munmap read recvfrom rt_sigreturn sendto socket vfork write

[Install]
WantedBy=multi-user.target
FROB_UNIT_EOF
    systemctl daemon-reload
    echo "wrote unit frob-deploy-display.service"
else
    echo "unit frob-deploy-display.service already up to date"
fi
if ! systemctl is-enabled --quiet "frob-deploy-display.service" 2>/dev/null; then
    systemctl enable "frob-deploy-display.service"
    echo "enabled frob-deploy-display.service"
fi
if ! systemctl is-active --quiet "frob-deploy-display.service" 2>/dev/null; then
    systemctl start "frob-deploy-display.service"
    echo "started frob-deploy-display.service"
fi
desired_mode="0750"
if [ ! -e "/var/lib/malmberg-display" ]; then
    mkdir -p "/var/lib/malmberg-display"
    echo "created /var/lib/malmberg-display"
fi
current_owner="$(stat -c "%U" "/var/lib/malmberg-display")"
if [ "$current_owner" != "malmberg-display" ]; then
    chown "malmberg-display":"malmberg-display" "/var/lib/malmberg-display"
    echo "chowned /var/lib/malmberg-display to malmberg-display"
fi
current_mode="$(stat -c "%a" "/var/lib/malmberg-display")"
if [ "${current_mode#0}" != "${desired_mode#0}" ]; then
    chmod "0750" "/var/lib/malmberg-display"
    echo "chmoded /var/lib/malmberg-display to 0750"
fi
echo "--- faces ---"
if ! id -u "malmberg-faces" >/dev/null 2>&1; then
    useradd --system --no-create-home --shell /usr/sbin/nologin "malmberg-faces"
    echo "created service user malmberg-faces"
else
    echo "service user malmberg-faces already present, skipping"
fi
desired_hash="06a3019aafcf30801692f60b64eedc23dd9b18068ca587cf2be0cbb3c011a3da"
if [ -f "/etc/systemd/system/frob-deploy-faces.service" ]; then
    current_hash="$(sha256sum "/etc/systemd/system/frob-deploy-faces.service" | cut -d" " -f1)"
else
    current_hash=""
fi
if [ "$current_hash" != "$desired_hash" ]; then
    cat > "/etc/systemd/system/frob-deploy-faces.service" <<'FROB_UNIT_EOF'
[Unit]
Description=frob deploy generated unit for faces

[Service]
User=malmberg-faces
NoNewPrivileges=yes
ProtectSystem=strict
PrivateTmp=yes
ReadWritePaths=/var/lib/malmberg/faces
CapabilityBoundingSet=
SystemCallFilter=brk close exit exit_group mmap munmap read rt_sigreturn write

[Install]
WantedBy=multi-user.target
FROB_UNIT_EOF
    systemctl daemon-reload
    echo "wrote unit frob-deploy-faces.service"
else
    echo "unit frob-deploy-faces.service already up to date"
fi
if ! systemctl is-enabled --quiet "frob-deploy-faces.service" 2>/dev/null; then
    systemctl enable "frob-deploy-faces.service"
    echo "enabled frob-deploy-faces.service"
fi
if ! systemctl is-active --quiet "frob-deploy-faces.service" 2>/dev/null; then
    systemctl start "frob-deploy-faces.service"
    echo "started frob-deploy-faces.service"
fi
desired_mode="0750"
if [ ! -e "/var/lib/malmberg/faces" ]; then
    mkdir -p "/var/lib/malmberg/faces"
    echo "created /var/lib/malmberg/faces"
fi
current_owner="$(stat -c "%U" "/var/lib/malmberg/faces")"
if [ "$current_owner" != "malmberg-faces" ]; then
    chown "malmberg-faces":"malmberg-faces" "/var/lib/malmberg/faces"
    echo "chowned /var/lib/malmberg/faces to malmberg-faces"
fi
current_mode="$(stat -c "%a" "/var/lib/malmberg/faces")"
if [ "${current_mode#0}" != "${desired_mode#0}" ]; then
    chmod "0750" "/var/lib/malmberg/faces"
    echo "chmoded /var/lib/malmberg/faces to 0750"
fi
echo "--- ingest ---"
if ! id -u "malmberg-ingest" >/dev/null 2>&1; then
    useradd --system --no-create-home --shell /usr/sbin/nologin "malmberg-ingest"
    echo "created service user malmberg-ingest"
else
    echo "service user malmberg-ingest already present, skipping"
fi
desired_hash="9cc313aca17535f4ee955ce07608d227134a5a50521da709ad379d6931c49543"
if [ -f "/etc/systemd/system/frob-deploy-ingest.service" ]; then
    current_hash="$(sha256sum "/etc/systemd/system/frob-deploy-ingest.service" | cut -d" " -f1)"
else
    current_hash=""
fi
if [ "$current_hash" != "$desired_hash" ]; then
    cat > "/etc/systemd/system/frob-deploy-ingest.service" <<'FROB_UNIT_EOF'
[Unit]
Description=frob deploy generated unit for ingest

[Service]
User=malmberg-ingest
NoNewPrivileges=yes
ProtectSystem=strict
PrivateTmp=yes
ReadWritePaths=/var/lib/malmberg/staging
CapabilityBoundingSet=
SystemCallFilter=brk close exit exit_group mmap munmap read rt_sigreturn write

[Install]
WantedBy=multi-user.target
FROB_UNIT_EOF
    systemctl daemon-reload
    echo "wrote unit frob-deploy-ingest.service"
else
    echo "unit frob-deploy-ingest.service already up to date"
fi
if ! systemctl is-enabled --quiet "frob-deploy-ingest.service" 2>/dev/null; then
    systemctl enable "frob-deploy-ingest.service"
    echo "enabled frob-deploy-ingest.service"
fi
if ! systemctl is-active --quiet "frob-deploy-ingest.service" 2>/dev/null; then
    systemctl start "frob-deploy-ingest.service"
    echo "started frob-deploy-ingest.service"
fi
desired_mode="0750"
if [ ! -e "/var/lib/malmberg/staging" ]; then
    mkdir -p "/var/lib/malmberg/staging"
    echo "created /var/lib/malmberg/staging"
fi
current_owner="$(stat -c "%U" "/var/lib/malmberg/staging")"
if [ "$current_owner" != "malmberg-ingest" ]; then
    chown "malmberg-ingest":"malmberg-ingest" "/var/lib/malmberg/staging"
    echo "chowned /var/lib/malmberg/staging to malmberg-ingest"
fi
current_mode="$(stat -c "%a" "/var/lib/malmberg/staging")"
if [ "${current_mode#0}" != "${desired_mode#0}" ]; then
    chmod "0750" "/var/lib/malmberg/staging"
    echo "chmoded /var/lib/malmberg/staging to 0750"
fi
echo "--- media_store ---"
if ! id -u "malmberg-ingest" >/dev/null 2>&1; then
    useradd --system --no-create-home --shell /usr/sbin/nologin "malmberg-ingest"
    echo "created service user malmberg-ingest"
else
    echo "service user malmberg-ingest already present, skipping"
fi
desired_mode="0750"
if [ ! -e "/srv/malmberg/media" ]; then
    mkdir -p "/srv/malmberg/media"
    echo "created /srv/malmberg/media"
fi
current_owner="$(stat -c "%U" "/srv/malmberg/media")"
if [ "$current_owner" != "malmberg-ingest" ]; then
    chown "malmberg-ingest":"malmberg-ingest" "/srv/malmberg/media"
    echo "chowned /srv/malmberg/media to malmberg-ingest"
fi
current_mode="$(stat -c "%a" "/srv/malmberg/media")"
if [ "${current_mode#0}" != "${desired_mode#0}" ]; then
    chmod "0750" "/srv/malmberg/media"
    echo "chmoded /srv/malmberg/media to 0750"
fi
echo "--- server_api ---"
if ! id -u "malmberg-api" >/dev/null 2>&1; then
    useradd --system --no-create-home --shell /usr/sbin/nologin "malmberg-api"
    echo "created service user malmberg-api"
else
    echo "service user malmberg-api already present, skipping"
fi
desired_hash="9d9909af6704b5b853d7afa1138c6f6c92e3141daa2bd5b4ef9e23b606116842"
if [ -f "/etc/systemd/system/frob-deploy-server_api.service" ]; then
    current_hash="$(sha256sum "/etc/systemd/system/frob-deploy-server_api.service" | cut -d" " -f1)"
else
    current_hash=""
fi
if [ "$current_hash" != "$desired_hash" ]; then
    cat > "/etc/systemd/system/frob-deploy-server_api.service" <<'FROB_UNIT_EOF'
[Unit]
Description=frob deploy generated unit for server_api

[Service]
User=malmberg-api
NoNewPrivileges=yes
ProtectSystem=strict
PrivateTmp=yes
ReadWritePaths=/var/lib/malmberg/api
CapabilityBoundingSet=CAP_NET_BIND_SERVICE
SystemCallFilter=accept bind brk clone close connect execve execveat exit exit_group fork listen mmap munmap read recvfrom rt_sigreturn sendto socket vfork write

[Install]
WantedBy=multi-user.target
FROB_UNIT_EOF
    systemctl daemon-reload
    echo "wrote unit frob-deploy-server_api.service"
else
    echo "unit frob-deploy-server_api.service already up to date"
fi
if ! systemctl is-enabled --quiet "frob-deploy-server_api.service" 2>/dev/null; then
    systemctl enable "frob-deploy-server_api.service"
    echo "enabled frob-deploy-server_api.service"
fi
if ! systemctl is-active --quiet "frob-deploy-server_api.service" 2>/dev/null; then
    systemctl start "frob-deploy-server_api.service"
    echo "started frob-deploy-server_api.service"
fi
desired_mode="0750"
if [ ! -e "/var/lib/malmberg/api" ]; then
    mkdir -p "/var/lib/malmberg/api"
    echo "created /var/lib/malmberg/api"
fi
current_owner="$(stat -c "%U" "/var/lib/malmberg/api")"
if [ "$current_owner" != "malmberg-api" ]; then
    chown "malmberg-api":"malmberg-api" "/var/lib/malmberg/api"
    echo "chowned /var/lib/malmberg/api to malmberg-api"
fi
current_mode="$(stat -c "%a" "/var/lib/malmberg/api")"
if [ "${current_mode#0}" != "${desired_mode#0}" ]; then
    chmod "0750" "/var/lib/malmberg/api"
    echo "chmoded /var/lib/malmberg/api to 0750"
fi
echo "install complete"
