#!/usr/bin/env bash
# frob deploy status.sh
# GENERATED by `frob deploy generate` -- DO NOT EDIT BY HAND.
# Re-run `frob deploy generate` to regenerate after a design change.
# frob-deploy-manifest-digest: 5b791d59d5ed3afe22289d66d609f13cbbc0d8cac49f277b0c6b97e0b80e25a5
set -euo pipefail

active="$(systemctl is-active "frob-deploy-backup.service" 2>/dev/null || true)"
enabled="$(systemctl is-enabled "frob-deploy-backup.service" 2>/dev/null || true)"
echo "unit=frob-deploy-backup.service node=backup active=$active enabled=$enabled"
active="$(systemctl is-active "frob-deploy-cloudsync.service" 2>/dev/null || true)"
enabled="$(systemctl is-enabled "frob-deploy-cloudsync.service" 2>/dev/null || true)"
echo "unit=frob-deploy-cloudsync.service node=cloudsync active=$active enabled=$enabled"
active="$(systemctl is-active "frob-deploy-display.service" 2>/dev/null || true)"
enabled="$(systemctl is-enabled "frob-deploy-display.service" 2>/dev/null || true)"
echo "unit=frob-deploy-display.service node=display active=$active enabled=$enabled"
if timeout 1 bash -c 'cat < /dev/null > /dev/tcp/127.0.0.1/8001' 2>/dev/null; then
    echo "unit=frob-deploy-display.service port=8001=open"
else
    echo "unit=frob-deploy-display.service port=8001=closed"
fi
active="$(systemctl is-active "frob-deploy-faces.service" 2>/dev/null || true)"
enabled="$(systemctl is-enabled "frob-deploy-faces.service" 2>/dev/null || true)"
echo "unit=frob-deploy-faces.service node=faces active=$active enabled=$enabled"
active="$(systemctl is-active "frob-deploy-ingest.service" 2>/dev/null || true)"
enabled="$(systemctl is-enabled "frob-deploy-ingest.service" 2>/dev/null || true)"
echo "unit=frob-deploy-ingest.service node=ingest active=$active enabled=$enabled"
active="$(systemctl is-active "frob-deploy-server_api.service" 2>/dev/null || true)"
enabled="$(systemctl is-enabled "frob-deploy-server_api.service" 2>/dev/null || true)"
echo "unit=frob-deploy-server_api.service node=server_api active=$active enabled=$enabled"
if timeout 1 bash -c 'cat < /dev/null > /dev/tcp/127.0.0.1/8000' 2>/dev/null; then
    echo "unit=frob-deploy-server_api.service port=8000=open"
else
    echo "unit=frob-deploy-server_api.service port=8000=closed"
fi
