#!/usr/bin/env bash
# frob deploy uninstall.sh
# GENERATED by `frob deploy generate` -- DO NOT EDIT BY HAND.
# Re-run `frob deploy generate` to regenerate after a design change.
# frob-deploy-manifest-digest: 5b791d59d5ed3afe22289d66d609f13cbbc0d8cac49f277b0c6b97e0b80e25a5
set -euo pipefail

echo "--- backup ---"
if systemctl is-active --quiet "frob-deploy-backup.service" 2>/dev/null; then
    systemctl stop "frob-deploy-backup.service"
fi
if systemctl is-enabled --quiet "frob-deploy-backup.service" 2>/dev/null; then
    systemctl disable "frob-deploy-backup.service"
fi
if [ -f "/etc/systemd/system/frob-deploy-backup.service" ]; then
    rm -f "/etc/systemd/system/frob-deploy-backup.service"
    systemctl daemon-reload
    echo "removed unit frob-deploy-backup.service"
fi
if [ -e "/var/lib/malmberg/backup-audit" ]; then
    rm -rf "/var/lib/malmberg/backup-audit"
    echo "removed /var/lib/malmberg/backup-audit"
fi
if id -u "malmberg-backup" >/dev/null 2>&1; then
    userdel "malmberg-backup"
    echo "removed service user malmberg-backup"
fi
echo "--- cloudsync ---"
if systemctl is-active --quiet "frob-deploy-cloudsync.service" 2>/dev/null; then
    systemctl stop "frob-deploy-cloudsync.service"
fi
if systemctl is-enabled --quiet "frob-deploy-cloudsync.service" 2>/dev/null; then
    systemctl disable "frob-deploy-cloudsync.service"
fi
if [ -f "/etc/systemd/system/frob-deploy-cloudsync.service" ]; then
    rm -f "/etc/systemd/system/frob-deploy-cloudsync.service"
    systemctl daemon-reload
    echo "removed unit frob-deploy-cloudsync.service"
fi
if [ -e "/var/lib/malmberg/cloud-staging" ]; then
    rm -rf "/var/lib/malmberg/cloud-staging"
    echo "removed /var/lib/malmberg/cloud-staging"
fi
if id -u "malmberg-cloudsync" >/dev/null 2>&1; then
    userdel "malmberg-cloudsync"
    echo "removed service user malmberg-cloudsync"
fi
echo "--- display ---"
if systemctl is-active --quiet "frob-deploy-display.service" 2>/dev/null; then
    systemctl stop "frob-deploy-display.service"
fi
if systemctl is-enabled --quiet "frob-deploy-display.service" 2>/dev/null; then
    systemctl disable "frob-deploy-display.service"
fi
if [ -f "/etc/systemd/system/frob-deploy-display.service" ]; then
    rm -f "/etc/systemd/system/frob-deploy-display.service"
    systemctl daemon-reload
    echo "removed unit frob-deploy-display.service"
fi
if [ -e "/var/lib/malmberg-display" ]; then
    rm -rf "/var/lib/malmberg-display"
    echo "removed /var/lib/malmberg-display"
fi
if id -u "malmberg-display" >/dev/null 2>&1; then
    userdel "malmberg-display"
    echo "removed service user malmberg-display"
fi
echo "--- faces ---"
if systemctl is-active --quiet "frob-deploy-faces.service" 2>/dev/null; then
    systemctl stop "frob-deploy-faces.service"
fi
if systemctl is-enabled --quiet "frob-deploy-faces.service" 2>/dev/null; then
    systemctl disable "frob-deploy-faces.service"
fi
if [ -f "/etc/systemd/system/frob-deploy-faces.service" ]; then
    rm -f "/etc/systemd/system/frob-deploy-faces.service"
    systemctl daemon-reload
    echo "removed unit frob-deploy-faces.service"
fi
if [ -e "/var/lib/malmberg/faces" ]; then
    rm -rf "/var/lib/malmberg/faces"
    echo "removed /var/lib/malmberg/faces"
fi
if id -u "malmberg-faces" >/dev/null 2>&1; then
    userdel "malmberg-faces"
    echo "removed service user malmberg-faces"
fi
echo "--- ingest ---"
if systemctl is-active --quiet "frob-deploy-ingest.service" 2>/dev/null; then
    systemctl stop "frob-deploy-ingest.service"
fi
if systemctl is-enabled --quiet "frob-deploy-ingest.service" 2>/dev/null; then
    systemctl disable "frob-deploy-ingest.service"
fi
if [ -f "/etc/systemd/system/frob-deploy-ingest.service" ]; then
    rm -f "/etc/systemd/system/frob-deploy-ingest.service"
    systemctl daemon-reload
    echo "removed unit frob-deploy-ingest.service"
fi
if [ -e "/var/lib/malmberg/staging" ]; then
    rm -rf "/var/lib/malmberg/staging"
    echo "removed /var/lib/malmberg/staging"
fi
if id -u "malmberg-ingest" >/dev/null 2>&1; then
    userdel "malmberg-ingest"
    echo "removed service user malmberg-ingest"
fi
echo "--- media_store ---"
if [ -e "/srv/malmberg/media" ]; then
    rm -rf "/srv/malmberg/media"
    echo "removed /srv/malmberg/media"
fi
if id -u "malmberg-ingest" >/dev/null 2>&1; then
    userdel "malmberg-ingest"
    echo "removed service user malmberg-ingest"
fi
echo "--- server_api ---"
if systemctl is-active --quiet "frob-deploy-server_api.service" 2>/dev/null; then
    systemctl stop "frob-deploy-server_api.service"
fi
if systemctl is-enabled --quiet "frob-deploy-server_api.service" 2>/dev/null; then
    systemctl disable "frob-deploy-server_api.service"
fi
if [ -f "/etc/systemd/system/frob-deploy-server_api.service" ]; then
    rm -f "/etc/systemd/system/frob-deploy-server_api.service"
    systemctl daemon-reload
    echo "removed unit frob-deploy-server_api.service"
fi
if [ -e "/var/lib/malmberg/api" ]; then
    rm -rf "/var/lib/malmberg/api"
    echo "removed /var/lib/malmberg/api"
fi
if id -u "malmberg-api" >/dev/null 2>&1; then
    userdel "malmberg-api"
    echo "removed service user malmberg-api"
fi
echo "uninstall complete"
