"""Idempotent provisioning for the Malmberg display role.

Invoked as::

    sudo python -m malmberg_display setup [--dry-run] [--no-enable] [--user USER]

Every step is idempotent.  Steps that cannot complete non-fatally (e.g.
playwright installation on low-RAM hardware) emit a warning and continue.

Exit codes:
  0  All required steps completed.
  1  A required step failed.
  2  Not running as root.
"""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
from pathlib import Path

from malmberg_core.hal.detect import _detect_profile, write_hardware_toml
from malmberg_core.hal.profile import HardwareProfile
from malmberg_core.logging import get_logger
from malmberg_core.provision import (
    DEFAULT_BRANCH,
    DEFAULT_REPO_DIR,
    DEFAULT_UPDATE_MINUTES,
    detect_repo_dir,
    install_github_autoupdate,
)

_log = get_logger(__name__)

# ---------------------------------------------------------------------------
# Platform validation
# ---------------------------------------------------------------------------

_MIN_PYTHON = (3, 10)
_REQUIRED_CMDS = ("systemctl",)


def validate_environment() -> list[str]:
    """Return a list of blocking problems in the current environment."""
    problems: list[str] = []

    if sys.platform != "linux":
        problems.append(
            f"Unsupported platform '{sys.platform}'; malmberg-display requires Linux."
        )

    if sys.version_info < _MIN_PYTHON:
        v = ".".join(str(x) for x in sys.version_info[:2])
        req = ".".join(str(x) for x in _MIN_PYTHON)
        problems.append(f"Python {req}+ required; found {v}.")

    for cmd in _REQUIRED_CMDS:
        if subprocess.run(["which", cmd], capture_output=True).returncode != 0:
            problems.append(
                f"Required command '{cmd}' not found. "
                "Install with: sudo apt install systemd"
            )

    # Warn (not block) if no display seems to be available.
    if not os.environ.get("DISPLAY") and not os.environ.get("WAYLAND_DISPLAY"):
        problems.append(
            "No DISPLAY or WAYLAND_DISPLAY environment variable found. "
            "Run from an active X or Wayland session, or set DISPLAY=:0 "
            "if the display will be started by the service."
        )

    return problems


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

_CONFIG_DIR = Path("/etc/malmberg")
_HARDWARE_TOML = _CONFIG_DIR / "hardware.toml"
_SYSTEMD_UNIT = Path("/etc/systemd/system/malmberg-display.service")

# X11 config to disable screen blanking system-wide.
_XORG_CONF_DIR = Path("/etc/X11/xorg.conf.d")
_XORG_BLANKING_CONF = _XORG_CONF_DIR / "10-malmberg-no-blanking.conf"

_XORG_BLANKING_CONTENT = """\
Section "ServerFlags"
    Option "BlankTime"  "0"
    Option "StandbyTime" "0"
    Option "SuspendTime" "0"
    Option "OffTime" "0"
EndSection

Section "Monitor"
    Identifier "Monitor0"
    Option "DPMS" "false"
EndSection
"""

# mpv configuration tuned per hardware profile.
_MPV_CONF_TEMPLATE = """\
# Malmberg display -- mpv configuration (auto-generated by setup)
# Hardware profile: {name}
hwdec={hwdec}
vo=gpu
fullscreen=yes
loop-file=no
quiet=yes
msg-level=all=error
"""

_UNIT_TEMPLATE = """\
[Unit]
Description=Malmberg Display
After=graphical.target network-online.target
Wants=graphical.target

[Service]
Type=simple
User={user}
WorkingDirectory={work_dir}
ExecStart={python} -m malmberg_display
Restart=on-failure
RestartSec=5
StandardOutput=journal
StandardError=journal
Environment=PYTHONUNBUFFERED=1
Environment=DISPLAY=:0
Environment=XAUTHORITY=/home/{user}/.Xauthority

[Install]
WantedBy=graphical.target
"""


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------


def run(args: argparse.Namespace) -> None:
    """Run all provisioning steps and print a summary."""
    dry = getattr(args, "dry_run", False)
    no_enable = getattr(args, "no_enable", False)
    # The display service should run as an unprivileged user that owns the X
    # session.  Default to the SUDO_USER (the person who ran sudo), or "pi".
    service_user = getattr(args, "user", None) or os.environ.get("SUDO_USER") or "pi"

    _require_root()

    problems = validate_environment()
    # Display env warning is non-blocking for setup (service sets DISPLAY=:0).
    blocking = [p for p in problems if "DISPLAY" not in p and "WAYLAND" not in p]
    for p in problems:
        if p not in blocking:
            _log.warning("Environment notice: %s", p)
    if blocking:
        _log.error("Cannot provision: environment checks failed.")
        for p in blocking:
            _log.error("  - %s", p)
        sys.exit(1)

    steps: list[tuple[str, str]] = []
    warnings: list[str] = []

    # 1. Hardware profile
    profile = _step_hardware(dry, warnings)
    steps.append(("Hardware profile", f"{_HARDWARE_TOML} ({profile.name})"))

    # 2. Screen blanking
    _step_no_blanking(dry, warnings)
    steps.append(("Screen blanking", "disabled via xorg config"))

    # 3. mpv configuration
    mpv_path = _step_mpv_conf(profile, service_user, dry)
    steps.append(("mpv config", str(mpv_path)))

    # 4. Playwright (optional, only if hardware supports it)
    playwright_msg = _step_playwright(profile, dry, warnings)
    steps.append(("playwright", playwright_msg))

    # 5. Systemd unit
    _step_unit(service_user, dry)
    steps.append(("Systemd unit", str(_SYSTEMD_UNIT)))

    # 6. Enable service (but do not start -- user must pair first).  Enabling
    #    wires it into graphical.target, so it auto-starts on every power-up
    #    once the desktop session (DISPLAY=:0) is up.
    if not no_enable:
        _step_enable(dry, warnings)
        steps.append(
            ("Service", "malmberg-display enabled; auto-starts at boot (pair first)")
        )
    else:
        steps.append(("Service", "skipped (--no-enable)"))

    # 7. Unattended GitHub updates.
    steps.append(("Auto-update", _step_auto_update(args, service_user, dry, warnings)))

    _print_summary(steps, warnings, service_user)


# ---------------------------------------------------------------------------
# Individual steps
# ---------------------------------------------------------------------------


def _step_hardware(dry: bool, warnings: list[str]) -> HardwareProfile:
    result = _detect_profile()
    if result.is_ok:
        profile = result.danger_ok
    else:
        profile = HardwareProfile.fallback()
        warnings.append(
            "Hardware auto-detection failed; using generic-x86 fallback. "
            f"Edit {_HARDWARE_TOML} manually if on a Raspberry Pi."
        )
    if not dry:
        write_hardware_toml(profile, _HARDWARE_TOML)
    _log.info("Hardware profile: %s", profile.name)
    return profile


def _step_no_blanking(dry: bool, warnings: list[str]) -> None:
    if _XORG_BLANKING_CONF.is_file():
        _log.info("Screen blanking already disabled (xorg config present).")
        return
    _log.info("Writing xorg config to disable screen blanking.")
    if dry:
        return
    try:
        _XORG_CONF_DIR.mkdir(parents=True, exist_ok=True)
        _XORG_BLANKING_CONF.write_text(_XORG_BLANKING_CONTENT)
    except OSError as exc:
        warnings.append(
            f"Could not write xorg blanking config: {exc}. "
            "Disable screen blanking manually: xset s off && xset -dpms"
        )
        return

    # Also disable blanking in the Pi boot config if present.
    for boot_cfg in (
        Path("/boot/firmware/config.txt"),
        Path("/boot/config.txt"),
    ):
        if boot_cfg.is_file():
            _add_to_pi_config(boot_cfg, "consoleblank=0")
            break


def _add_to_pi_config(path: Path, line: str) -> None:
    """Append *line* to *path* if it is not already present."""
    text = path.read_text()
    if line in text:
        return
    with open(path, "a") as f:
        f.write(f"\n# Added by malmberg setup\n{line}\n")
    _log.info("Added '%s' to %s.", line, path)


def _step_mpv_conf(
    profile: HardwareProfile,
    service_user: str,
    dry: bool,
) -> Path:
    hwdec = "auto" if profile.hw_video_decode else "no"
    content = _MPV_CONF_TEMPLATE.format(
        name=profile.name,
        hwdec=hwdec,
    )
    # Write to the service user's home directory mpv config.
    home = _user_home(service_user)
    mpv_dir = home / ".config" / "mpv"
    mpv_conf = mpv_dir / "mpv.conf"
    _log.info("Writing mpv config to %s.", mpv_conf)
    if not dry:
        mpv_dir.mkdir(parents=True, exist_ok=True)
        mpv_conf.write_text(content)
    return mpv_conf


def _step_playwright(
    profile: HardwareProfile,
    dry: bool,
    warnings: list[str],
) -> str:
    if not profile.playwright_supported:
        return f"skipped (not supported on {profile.name})"

    # Check if playwright is already installed.
    check = subprocess.run(
        [sys.executable, "-c", "import playwright"],
        capture_output=True,
    )
    if check.returncode == 0:
        return "already installed"

    # Prompt -- only proceed if stdin is a tty (interactive run).
    if not sys.stdin.isatty():
        warnings.append(
            "playwright is not installed and this hardware supports it. "
            "Install with: uv sync --extra web-overlays && "
            "uv run playwright install chromium"
        )
        return "not installed (non-interactive run)"

    print()
    print(
        f"This hardware profile ({profile.name}) supports web overlays "
        "(clock, weather).\nThey require playwright + Chromium (~500 MB download)."
    )
    answer = input("Install playwright and Chromium? [y/N] ").strip().lower()
    if answer != "y":
        warnings.append(
            "playwright not installed.  To enable web overlays later: "
            "uv sync --extra web-overlays && uv run playwright install chromium"
        )
        return "skipped (user declined)"

    if not dry:
        result = subprocess.run(
            [sys.executable, "-m", "pip", "install", "playwright"],
            capture_output=True,
            text=True,
        )
        if result.returncode != 0:
            warnings.append(f"playwright pip install failed: {result.stderr.strip()}")
            return "install failed (see warnings)"
        subprocess.run(
            [sys.executable, "-m", "playwright", "install", "chromium"],
            check=False,
        )
    return "installed"


def _step_unit(service_user: str, dry: bool) -> None:
    home = _user_home(service_user)
    content = _UNIT_TEMPLATE.format(
        user=service_user,
        work_dir=str(home),
        python=sys.executable,
    )
    _log.info("Writing systemd unit to %s.", _SYSTEMD_UNIT)
    if dry:
        return
    _SYSTEMD_UNIT.write_text(content)
    subprocess.run(["systemctl", "daemon-reload"], check=False)


def _step_auto_update(
    args: argparse.Namespace,
    service_user: str,
    dry: bool,
    warnings: list[str],
) -> str:
    """Install a timer that pulls origin/<branch> and restarts the display."""
    if getattr(args, "no_auto_update", False):
        return "disabled (--no-auto-update)"

    repo_dir = Path(
        getattr(args, "repo_dir", None)
        or detect_repo_dir(Path(__file__))
        or DEFAULT_REPO_DIR
    )
    branch = getattr(args, "branch", None) or DEFAULT_BRANCH
    minutes = int(getattr(args, "update_interval", None) or DEFAULT_UPDATE_MINUTES)

    summary, warns = install_github_autoupdate(
        repo_dir=repo_dir,
        branch=branch,
        minutes=minutes,
        restart_service="malmberg-display",
        run_as_user=service_user,
        dry=dry,
        extras=("display",),  # keep pygame/mpv/Pillow across auto-updates
    )
    warnings.extend(warns)
    return summary


def _step_enable(dry: bool, warnings: list[str]) -> None:
    _log.info("Enabling malmberg-display service.")
    if dry:
        return
    result = subprocess.run(
        ["systemctl", "enable", "malmberg-display"],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        warnings.append(
            f"systemctl enable failed: {result.stderr.strip()}. "
            "Enable manually: sudo systemctl enable malmberg-display"
        )


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _require_root() -> None:
    if os.getuid() != 0:
        _log.error(
            "The setup command must be run as root: "
            "sudo uv run python -m malmberg_display setup"
        )
        sys.exit(2)


def _user_home(username: str) -> Path:
    """Return the home directory for *username*, defaulting to /home/<username>."""
    import pwd as _pwd

    try:
        return Path(_pwd.getpwnam(username).pw_dir)
    except KeyError:
        return Path(f"/home/{username}")


def _print_summary(
    steps: list[tuple[str, str]],
    warnings: list[str],
    service_user: str,
) -> None:
    width = 60
    print()
    print("=" * width)
    print("  Malmberg Display -- Provisioning Complete")
    print("=" * width)
    for label, detail in steps:
        print(f"  {label:<24} {detail}")
    if warnings:
        print()
        print("  Warnings:")
        for w in warnings:
            print(f"    ! {w}")
    print()
    print("  Next steps:")
    print("    1. sudo systemctl start malmberg-display")
    print("    2. Enter the PIN shown on your server to pair.")
    print()
    print("  Or connect directly to a known server:")
    print("    echo 'server_url = \"http://<server-ip>:8444\"' \\")
    print(f"      >> /home/{service_user}/.config/malmberg/display.toml")
    print()
    print("  Verify:  systemctl status malmberg-display")
    print("           curl http://localhost:8443/status")
    print("=" * width)
    print()
